### ISSUE TITLE
Steady rise in memory consumption

### ISSUE THREAD

**Issue by saschajullmann** [zammad/zammad-docker-compose#82] opened 2018-08-02 07:06 UTC
### Infos:

* Docker version: 18.06.0-ce
* Docker-compose version: 1.21.2
* Operating system (Docker host): Ubuntu 18.04
* Hardware: AWS EC2 c5.xlarge (4 cores and 8gig ram)

### Expected behavior:

* Memory consumption stays relatively flat.

### Actual behavior:

* Memory consumptions rises throughout the day until we have to restart the containers.

### Steps to reproduce the behavior:

* Pull the zammad-docker-compose repo, run "docker-compose up -d", load a few initial tickets and let a few people work on it simultaneously.

Hi,

we started running zammad in production and are having trouble with the memory consumption. We successfully migrated from OTRS to zammad and imported around 115K tickets in the process. We have around 10 agents working in zammad simultaneously.
What we noticed on the first day after the migration is that the memory consumption just keeps rising. It rose all throughout the day to a point where the system was unusable and I had to reboot the server via the AWS management console (cause I couldn't even restart the containers on the server). 
Afterwards the memory consumption was at around 4gig. That was yesterday evening and this morning it's back at 5.2gig and keeps rising.

I have swap enabled on this server but it's not being used.

Is anybody else experiencing these issues? I'm currently thinking it might be due to elasticsearch but I'm not entirely sure and don't really know how to debug this issue.

Any ideas?

Best regards
Sascha

EDIT
I just noticed that the issue seems to lie within the scheduler container. After restarting this container the memory consumption dropped to around 4gig. It keeps rising fast though.

**Comment by thorsteneckel** [comment] 2018-08-02 09:27
> We successfully migrated from OTRS to zammad and imported around 115K tickets in the process.
Holy moly! I love it 😍 

However, I don't think that it's caused by the docker(-composer) setup but is an application issue. Actually I think it's a duplicate of https://github.com/zammad/zammad/issues/2108

Would be cool if you could add some information and numbers to the issue like that you're using docker, the number of tickets (open), agents, active users, overviews etc.

Thanks! I'm closing here.

**Closed by thorsteneckel** 2018-08-02 09:27 UTC
