### ISSUE TITLE
Invalid format of target version: `VERSION=latest`

### ISSUE THREAD

**Issue by eugenewere** [zammad/zammad-docker-compose#320] opened 2022-12-06 17:51 UTC
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
initialising / updating database...
I, [2022-12-06T17:44:48.516237 #22-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T17:44:48.516389 #22-8280]  INFO -- : Using Redis as web socket session store.
Database 'zammad_production' already exists
I, [2022-12-06T17:44:50.940829 #23-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T17:44:50.940981 #23-8280]  INFO -- : Using Redis as web socket session store.
rake aborted!
Invalid format of target version: `VERSION=latest`
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/tasks/database_tasks.rb:263:in `check_target_version'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/tasks/database_tasks.rb:232:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:90:in `each'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
initialising / updating database...
I, [2022-12-06T17:45:05.147799 #22-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T17:45:05.148009 #22-8280]  INFO -- : Using Redis as web socket session store.
Database 'zammad_production' already exists
I, [2022-12-06T17:45:07.882517 #23-8280]  INFO -- : Using memcached as Rails cache store.
I, [2022-12-06T17:45:07.882680 #23-8280]  INFO -- : Using Redis as web socket session store.

**Comment by MrGeneration** [comment] 2022-12-06 18:12
Duplicate of #319

**Closed by MrGeneration** 2022-12-06 18:12 UTC
Labels: duplicate
