### ISSUE TITLE
 Can't find config setting 'es_url'

### ISSUE THREAD

**Issue by Zegorax** [zammad/zammad-docker-compose#63] opened 2018-01-11 12:33 UTC
### Infos:

* Docker version: Docker version 17.12.0-ce, build c97c6d6
* Docker-compose version: docker-compose version 1.17.0, build ac53b73
* Operating system (Docker host): Linux 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior:
Working ?

### Actual behavior:
Not working. Here's the error in init container :

```zammad-init_1           |       /opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_url' (RuntimeError)

zammad-init_1           |        from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:37:in `perform'

zammad-init_1           |       from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:37:in `eval'

zammad-init_1           |       from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:37:in `perform'

zammad-init_1           |       from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'

zammad-init_1           |       from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'

zammad-init_1           |       from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'

zammad-init_1           |       from /usr/local/bundle/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'

zammad-init_1           |       from /usr/local/bundle/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'

zammad-init_1           |       from /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'

zammad-init_1           |       from bin/rails:4:in `require'

zammad-init_1           |       from bin/rails:4:in `<main>'```

### Steps to reproduce the behavior:

Here's my docker-compose file :

```version: '2'
services:

  zammad-backup:
    environment:
      - ES_URL="http://localhost:9200"
    command: ["zammad-backup"]
    network_mode: bridge
    depends_on:
      - zammad-railsserver
    entrypoint: /usr/local/bin/backup.sh
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    links:
      - zammad-postgresql
    restart: always
    volumes:
      - ./zammad-backup:/var/tmp/zammad
      - ./zammad-data:/opt/zammad

  zammad-elasticsearch:
    environment:
      - ES_URL="http://localhost:9200"
    network_mode: bridge
    image: ${IMAGE_REPO}:zammad-elasticsearch${VERSION}
    restart: always
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  zammad-init:
    network_mode: bridge
    environment:
      - ES_URL="http://localhost:9200"
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: on-failure
    volumes:
      - ./zammad-data:/opt/zammad

  zammad-memcached:
    network_mode: bridge
    environment:
      - ES_URL="http://localhost:9200"
    command: ["zammad-memcached"]
    image: ${IMAGE_REPO}:zammad-memcached${VERSION}
    restart: always

  zammad-nginx:
    environment:
      - ES_URL="http://localhost:9200"
    network_mode: bridge
    command: ["zammad-nginx"]
    depends_on:
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: always
    volumes:
      - ./zammad-data:/opt/zammad
    ports:
      - 50010:80

  zammad-postgresql:
    environment:
      - ES_URL="http://localhost:9200"
    network_mode: bridge
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    restart: always
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  zammad-railsserver:
    environment:
      - ES_URL="http://localhost:9200"
    network_mode: bridge
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: always
    volumes:
      - ./zammad-data:/opt/zammad

  zammad-scheduler:
    environment:
      - ES_URL="http://localhost:9200"
    network_mode: bridge
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: always
    volumes:
      - ./zammad-data:/opt/zammad

  zammad-websocket:
    environment:
      - ES_URL="http://localhost:9200"
    network_mode: bridge
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-postgresql
      - zammad-memcached
    restart: always
    volumes:
      - ./zammad-data:/opt/zammad
```

As you can see, I tried to add ES_URL everywhere but it didn't work. So I don't know really what to do. 

Do you have an idea ?

**Comment by monotek** [comment] 2018-01-11 23:20
Where do you take this env var from?
It just not exists.

Check the entry point for possible variables:
https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh

Elasticsearch host is set by ELASTICSEARCH_HOST.

es_host is a ruby setting and no environment variable.

**Comment by Zegorax** [comment] 2018-01-15 13:02
Hello,
I added it because it wasn't working in the first place. If you take the docker-compose from the docs, nothing will get back up.

**Comment by monotek** [comment] 2018-01-15 13:39
Settings a ES_URL env var does nothing. Its completely ignored.

So you say "docker-compose stop && docker-compose start" do not work?

I can't reproduce this.

**Comment by Zegorax** [comment] 2018-01-15 17:34
I don't know why, now it works  ¯\_(ツ)_/¯

**Comment by monotek** [comment] 2018-01-15 17:42
OK. Closing for now... Feel free to reopen when you can reproduce...

**Closed by monotek** 2018-01-15 17:42 UTC

**Comment by Zegorax** [comment] 2018-01-16 06:36
I found out what was causing the problem. For my server infrastructure, I need to add network_mode: bridge to every containter. Once I do that, elasticsearch is not able to boot and throw this error :

zammad-elasticsearch_1  | [2018-01-16T06:36:18,261][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [aggs-matrix-stats]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,261][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [ingest-common]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,261][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [lang-expression]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,261][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [lang-groovy]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,261][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [lang-mustache]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,261][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [lang-painless]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,262][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [parent-join]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,262][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [percolator]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,262][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [reindex]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,262][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [transport-netty3]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,262][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded module [transport-netty4]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,263][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded plugin [ingest-attachment]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,263][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded plugin [ingest-geoip]
zammad-elasticsearch_1  | [2018-01-16T06:36:18,263][INFO ][o.e.p.PluginsService     ] [5VfZZWx] loaded plugin [ingest-user-agent]
zammad-elasticsearch_1  | [2018-01-16T06:36:20,644][INFO ][o.e.d.DiscoveryModule    ] [5VfZZWx] using discovery type [zen]
zammad-elasticsearch_1  | [2018-01-16T06:36:21,370][INFO ][o.e.n.Node               ] initialized
zammad-elasticsearch_1  | [2018-01-16T06:36:21,370][INFO ][o.e.n.Node               ] [5VfZZWx] starting ...
zammad-elasticsearch_1  | [2018-01-16T06:36:21,552][INFO ][o.e.t.TransportService   ] [5VfZZWx] publish_address {172.17.0.7:9300}, bound_addresses {0.0.0.0:9300}
zammad-elasticsearch_1  | [2018-01-16T06:36:21,565][INFO ][o.e.b.BootstrapChecks    ] [5VfZZWx] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
zammad-elasticsearch_1  | ERROR: [1] bootstrap checks failed
zammad-elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
zammad-elasticsearch_1  | [2018-01-16T06:36:21,574][INFO ][o.e.n.Node               ] [5VfZZWx] stopping ...
zammad-elasticsearch_1  | [2018-01-16T06:36:21,652][INFO ][o.e.n.Node               ] [5VfZZWx] stopped
zammad-elasticsearch_1  | [2018-01-16T06:36:21,653][INFO ][o.e.n.Node               ] [5VfZZWx] closing ...
zammad-elasticsearch_1  | [2018-01-16T06:36:21,680][INFO ][o.e.n.Node               ] [5VfZZWx] closed

**Comment by monotek** [comment] 2018-01-16 07:03
The error is not network related:

ERROR: [1] bootstrap checks failed
zammad-elasticsearch_1 | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

**Comment by Zegorax** [comment] 2018-01-16 18:43
So, it started again without problems. I don't know what was happening in the first place.
