### ISSUE TITLE
Branding logo not found

### ISSUE THREAD

**Issue by xjimbob** [zammad/zammad-docker-compose#360] opened 2023-07-03 03:40 UTC
# Infos

* Docker version: 23.0.0
* Docker-compose version: 2.15.1
* Operating system (Docker host): Ubuntu 22.04.2 LTS

# Expected behavior

* Add my branding logo and it shows up on the login page.

# Actual behavior

* I can add the logo in the branding section but when I reload the page or go to the login page it does show. In the logs for nginx it says that that the .png doesn't exist.

> 2023/07/03 03:21:45 [error] 14#14: *33 open() "/opt/zammad/public/assets/images/74e8e35c65ab566e671a59dd690139ba.png" failed (2: No such file or directory), client: 192.168.2.79, server: _, request: "GET /assets/images/74e8e35c65ab566e671a59dd690139ba.png HTTP/1.1", host: "support.website.com", referrer: "https://support.website.com/"
> 192.168.2.79 - - [03/Jul/2023:03:21:45 +0000] "GET /assets/images/74e8e35c65ab566e671a59dd690139ba.png HTTP/1.1" 404 181 "https://support.website.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

It is run behind a proxy, nginx proxy manager, but it worked fine before I updated to 6.0. If I navigate to the folder inside the nginx container, the file isn't there. If I navigate to the folder inside the railsserver container the image shows up there.

I have tried to reload the logo several times but it doesn't work.

Should it be reading it from the `zammad-var` volume? This may be another issue but there is nothing inside the `zammad-var` other than a `README.md` and `zammad.ready` file.

# Steps to reproduce the behavior

* Update to 6.0?

**Comment by MrGeneration** [comment] 2023-07-03 15:27
Duplicate of #354

**Closed by MrGeneration** 2023-07-03 15:27 UTC
Labels: duplicate
